export const CACHE_DEPENDENCY_MODULE = "CACHE_DEPENDENCY_MODULE";
export const CACHE_DEPENDENCY_KEY_METADATA = "CACHE_DEPENDENCY_KEY_METADATA";
export const CACHE_DEPENDENCY_PREFIX_CACHE_KEY = "cache-dependency:";
