export const CACHE_DEPENDENCY_MODULE = "CACHE_DEPENDENCY_MODULE";
export const CACHE_DEPENDENCY_MODULE_OPTIONS = "CACHE_DEPENDENCY_MODULE_OPTIONS";
export const CACHE_DEPENDENCY_KEY_METADATA = "CACHE_DEPENDENCY_KEY_METADATA";
export const CLEAR_CACHE_DEPENDENCIES_KEY_MATADATA = "CLEAR_CACHE_DEPENDENCIES_KEY_MATADATA";
export const CACHE_DEPENDENCY_PREFIX_CACHE_KEY = "cache-dependency:";

export const CACHE_DEPENDENCY_PUBSUB_DELETE_CHANNEL_EVENT = "CACHE_DEPENDENCY_PUBSUB_DELETE_CHANNEL_EVENT";
