name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: node:15
      env:
        REDIS_HOST: redis
    services:
      redis:
        image: redis
        ports:
          - "6379:6379"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node
      - name: Install npm packages
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Test monorepo packages
        if: github.repository != 'anchan828/nest-lerna-template'
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm test
          debug: true
